import "./globals.css";
import type { Metadata } from "next";
import { Instrument_Sans, Cal_Sans } from "next/font/google";

const body = Instrument_Sans({ subsets: ["latin"], variable: "--font-body", display: "swap" });
const display = Cal_Sans({ subsets: ["latin"], weight: ["400"], variable: "--font-title", display: "swap" });

export const metadata: Metadata = {
    title: "Owen's Pizzeria",
    description: "Generated by create next app",
};

export default function RootLayout({ children }: { children: React.ReactNode }) {
    return (
        <html lang="en" className={`${body.variable} ${display.variable}`}>
            <body className="font-body">{children}</body>
        </html>
    );
}
